from .alexnet import *
from .vggnet import *
from .resnet import *
from .squeezenet import *
from .googlenet import *
from .xception import *
from .densenet import *
from .mobilenet import *
from .mobilenetv2 import *
from .mobilenetv3 import *
from .ghostnet import *
from .shufflenet import *
from .shufflenetv2 import *
from .mnasnet import *
from .efficientnet import *
from .efficientnetv2 import *
from .mlp_mixer import *
from .resmlp import *
from .rexnet import *
from .regnet import *
from .vision_transformer import *
from .convmixer import *
from .convnext import *
from .vgnet import *

from . import gan
from . import vae
from . import seg
from . import det